name: Qweb Service Web

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Download flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Enable Flutter web
      run: flutter config --enable-web

    - name: Fluuter Pub-get
      run: flutter pub get
      
    - name: Build web Qwebapp
      run: flutter build web

 
