name: Qweb Service Web

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Flutter
      uses: subosito/flutter-action@v1
      with:
        channel: 'dev'

    - name: Actulizar flutter
      run:  flutter upgrade

    - name: Realizar flutter pub get 
      run:  flutter pub get

    - name: Realizar flutter pub upgrade get 
      run:  flutter pub upgrade
    
    - name: Enable Flutter web
      run: flutter config --enable-web

    - name: Install dependeces
      run: flutter packages get

    - name: Build web Qwebapp
      run: flutter build web

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.token }}
        publish_dir: ./build/web